### ISSUE TITLE
GUI interface to define modules

### ISSUE THREAD

**Issue by dalcde** [SpectralSequences/rust_webserver#12]
Work started in https://github.com/hoodmane/rust_ext/commit/dd6047162082c5e153881d832f9d3339c7aa7e6a

# Todo
 - [x] Respect `algebra` option
 - [ ] Support modules other than finite dimensional module
 - [ ] Support Milnor algebra profiles + validation
 - [ ] Validate actions before download
 - [ ] Better user interface
   - [ ] Highlight class when hovering over
   - [ ] Display existing actions with coefficients some way
 - [ ] Better integration with resolver
 - [ ] Link to this from front page
 - [ ] Better display of FD module (vary the sides of the bent action lines)
